apiVersion: 1

datasources:
  - id: 1
    orgId: 1
    name: PostgreSQL
    type: postgres
    typeLogoUrl: public/app/plugins/datasource/postgres/img/postgresql_logo.svg
    access: proxy
    url: ${POSTGRES_HOST}
    password: ${POSTGRES_PASSWORD}
    user: grafana
    database: ${POSTGRES_DB}
    basicAuth: false
    isDefault: true
    jsonData:
      postgresVersion: 1200
      timescaledb: true
      sslmode: disable
    readOnly: false
